apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-app-toolkit-kubecon
spec:
  title: End-to-end workflow with Application Toolkit
  description: Learn how Application Toolkit can help you create an end-to-end workflow
  url: https://github.com/vmware-tanzu-labs/lab-app-toolkit-kubecon
  workshop:
    files:
      - image:
          url: $(image_repository)/lab-app-toolkit-kubecon-files:latest
        includePaths:
          - /workshop/**
          - /exercises/**
    packages:
      - name: tce
        files:
          - image:
              url: ghcr.io/vmware-tanzu-labs/educates-extension-packages/tce-0.12:sha-5f9081f
  session:
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      vcluster:
        enabled: true
        resources:
          syncer:
            memory: 768Mi
          k3s:
            memory: 1Gi
        ingress:
          enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
      git:
        enabled: true
      editor:
        enabled: true
    objects:
      - apiVersion: kappctrl.k14s.io/v1alpha1
        kind: App
        metadata:
          name: kapp-controller.community.tanzu.vmware.com.0.38.3
          namespace: $(session_namespace)-vc
        spec:
          noopDelete: true
          syncPeriod: 24h
          cluster:
            namespace: default
            kubeconfigSecretRef:
              name: $(vcluster_secret)
              key: config
          fetch:
            - imgpkgBundle:
                image: projects.registry.vmware.com/tce/kapp-controller@sha256:3206554c308837edec6b50ae3082ed15c025f0d6a1bc7f3b2ac3602249c8fae5
          template:
            - ytt:
                paths:
                  - config/
            - kbld:
                paths:
                  - "-"
                  - .imgpkg/images.yml
          deploy:
            - kapp: {}
      - apiVersion: kappctrl.k14s.io/v1alpha1
        kind: App
        metadata:
          name: secretgen-controller.community.tanzu.vmware.com.0.8.0
          namespace: $(session_namespace)-vc
        spec:
          noopDelete: true
          syncPeriod: 24h
          cluster:
            namespace: default
            kubeconfigSecretRef:
              name: $(vcluster_secret)
              key: config
          fetch:
            - imgpkgBundle:
                image: projects.registry.vmware.com/tce/secretgen-controller@sha256:e9631ae47719e5f3344589c40188206233e87efc8a58ab965a43dba3bc7787c0
          template:
            - ytt:
                paths:
                  - config/
            - kbld:
                paths:
                  - '-'
                  - .imgpkg/images.yml
          deploy:
            - kapp: {}
