---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  buildImage:
    image: registry-lab-app-toolkit-kubecon-w01-s001.educates-local-dev.xyz/kp@sha256:fc8ae4eb09a1cce57aade5a613af8d7591ea3a90870faf75b96e8e496907aa7b
  id: io.buildpacks.stacks.bionic
  runImage:
    image: registry-lab-app-toolkit-kubecon-w01-s001.educates-local-dev.xyz/kp@sha256:25e9c561ee4a9f8d58c52d6f889c2d925542af9de4c7a8c9749e7b7ba88cfc8f
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  sources:
    - image: registry-lab-app-toolkit-kubecon-w01-s001.educates-local-dev.xyz/kp@sha256:d1aa5acef3e0ee9c5a5fc474e1d7e90a6426e824dcd63fe8584ea2eec7d40555
    - image: registry-lab-app-toolkit-kubecon-w01-s001.educates-local-dev.xyz/kp@sha256:ec864abb50c90c318457a9c921a513e3279fda53cfa74667d76a6cd43f20e61e
