---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  buildImage:
    image: paketobuildpacks/build:1.1.61-base-cnb
  id: io.buildpacks.stacks.bionic
  runImage:
    image: paketobuildpacks/run:1.1.61-base-cnb
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  sources:
    - image: gcr.io/paketo-buildpacks/java:6.21.0
    - image: gcr.io/paketo-buildpacks/go:1.4.0
